-- AlterTable
ALTER TABLE "User" ALTER COLUMN "first_name" DROP NOT NULL,
ALTER COLUMN "first_name" DROP DEFAULT,
ALTER COLUMN "last_name" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "adress" DROP NOT NULL,
ALTER COLUMN "region" DROP NOT NULL;
